version: "3.8"
services:
    name-service:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"
        volumes:
            # setup file or folder public
            - name-service:/app/public
        network_mode: bridge
        extra_hosts:
            - "host.docker.internal:host-gateway"
volumes:
    name-service:
        external: false
